app/urls.py
from django.urls import path

from . import views
from django.views.generic import RedirectView
from .views import (

    TestView,
    LogoutView,
    CoursesView,
    DetailView,
    CourseByUserListView,
    LessonView,
    CourseWorkView,
    DiplomaView,
    add_to_course,
)


app_name = 'app'
urlpatterns = [
    path('', CoursesView.as_view(), name='courses'),
    path('details/<int:pk>/', DetailView.as_view(), name='details'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('article/', TestView.as_view(), name='article'),
    path('coursework/', CourseWorkView.as_view(), name='coursework'),
    path('diploma/', DiplomaView.as_view(), name='diploma'),
    path('my_courses/', CourseByUserListView.as_view(), name='my_courses'),
    path('lesson/', LessonView.as_view(), name='lesson'),

    path('upload-video', views.Upload_file, name='upload-video'),
    path('add-to-course/<int:pk>/', add_to_course, name='add-to-course'),
]

education/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'), name='app'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
else:
    urlpatterns += staticfiles_urlpatterns()

app/models/course.py
from django.db import models
from django.conf import settings

from .description_course import DescriptionCourse
from django.contrib.auth.models import User



class Course(models.Model):
    student = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    description_course = models.ForeignKey(DescriptionCourse, verbose_name = 'Описание курса', on_delete=models.CASCADE)

    test = models.URLField(verbose_name='Тест')
    mark = models.PositiveIntegerField(verbose_name='Итоговый балл')
    sertificate = models.BooleanField(verbose_name='Наличие сертификата', default=False)

    def __str__(self):
        return str(self.pk)

    class Meta:
        """Meta"""

        verbose_name = 'Курс'
        verbose_name_plural = 'Курсы'

app/models/lesson.py
from django.db import models
from transliterate import translit
from app.models import Course
from embed_video.fields import EmbedVideoField

def upload_location(instance,filename):
  return "%s/%s" %('video',translit(filename,'ru',reversed=True))

class Lesson(models.Model):
    course = models.ForeignKey(Course, verbose_name='Урок', on_delete=models.CASCADE, null=True)
    video = EmbedVideoField(blank=True, null=True, verbose_name='Видео')
    task = models.CharField(verbose_name='Тема',max_length=50)
    name = models.CharField(verbose_name='Название',max_length=256)
    teacher = models.CharField(verbose_name='ФИО преподавателя',max_length=128)
    homework = models.URLField(verbose_name='Домашнее задание')
    mark = models.PositiveIntegerField(verbose_name='Оценка', null=True, blank=True)
    answer = models.FileField(verbose_name='Домашняя работа', upload_to='media/', null=True, blank=True)


    class Meta:
        """Meta"""

        verbose_name = 'Урок'
        verbose_name_plural = 'Уроки'

app/templates/central/article.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'central/css/style.css' %}" type="text/css"/>


<p class="title">Напиши свою статью!</p>
<form method="post">
    {% csrf_token %}
    <div class="form-group">
    <label for="exampleInputEmail1">Заголовок статьи</label>
    <input type="text" name="title" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
        <div class="form-group">
            <label for="exampleInputEmail2">Фамилия Имя Отчество</label>
            <input type="text" name="name" class="form-control" id="exampleInputEmail2" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail3">Учебное заведение</label>
            <input type="text" name="university" class="form-control" id="exampleInputEmail3" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail4">Город, Страна</label>
            <input type="text" name="address" class="form-control" id="exampleInputEmail4" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail5">Электронная почта</label>
            <input type="text" name="email" class="form-control" id="exampleInputEmail5" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail6">Аннотация</label>
            <textarea type="text" name="annotation"  class="form-control" rows="3" id="exampleInputEmail6"></textarea>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail7">Введение</label>
            <textarea type="text" name="introduction"  class="form-control" rows="3" id="exampleInputEmail7"></textarea>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail8">Текст статьи</label>
            <textarea type="text" name="article"  class="form-control" rows="7" id="exampleInputEmail8"></textarea>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail9">Заключение</label>
            <textarea type="text" name="conclusion"  class="form-control" rows="3" id="exampleInputEmail9"></textarea>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail10">Литература</label>
            <textarea type="text" name="literature"  class="form-control" rows="3" id="exampleInputEmail10"></textarea>

        </div>
<button type="submit" class="btn btn-primary" id="get">Получить файл</button>

</form>


{% endblock %}

app/templates/central/courses.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    {% for event in events %}
    <ul>
        <div class="card" style="width: 18rem;">
            <img src="{{ event.image.url }}" class="card-img-top" alt="">
                <div class="card-body">
                    <h5 class="card-title">{{ event.name }}</h5>
                    <p class="card-text">{{ event.task }}</p>
                    <p class="card-text">{{ event.university }}</p>
                    <a href="{% url 'app:details' event.id %}" class="btn btn-primary">Подробнее</a>
                </div>
        </div>
</ul>
    {% endfor %}
</div>

{% endblock %}

app/templates/central/coursework.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'central/css/style.css' %}" type="text/css"/>


<p class="title">Курсовая работа</p>
<form method="post">
    {% csrf_token %}
    <div class="form-group">
    <label for="exampleInputEmail1">Университет</label>
    <input type="text" name="university" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
        <div class="form-group">
            <label for="exampleInputEmail2">Институт</label>
            <input type="text" name="institute" class="form-control" id="exampleInputEmail2" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail3">Кафедра</label>
            <input type="text" name="kafedra" class="form-control" id="exampleInputEmail3" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail4">Направление</label>
            <input type="text" name="way" class="form-control" id="exampleInputEmail4" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail5">Тема курсовой работы</label>
            <input type="text" name="task" class="form-control" id="exampleInputEmail5" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail6">Курс</label>
            <textarea type="text" name="number"  class="form-control" rows="1" id="exampleInputEmail6"></textarea>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail7">Номер группы</label>
            <textarea type="text" name="group"  class="form-control" rows="1" id="exampleInputEmail7"></textarea>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail8">Год</label>
            <textarea type="text" name="year"  class="form-control" rows="1" id="exampleInputEmail8"></textarea>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail9">Фио студента</label>
            <textarea type="text" name="student"  class="form-control" rows="1" id="exampleInputEmail9"></textarea>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail10">Ученая степень преподавателя</label>
            <textarea type="text" name="degree"  class="form-control" rows="1" id="exampleInputEmail10"></textarea>
        </div>
    <div class="form-group">
            <label for="exampleInputEmail11">Фио преподавателя</label>
            <textarea type="text" name="teacher"  class="form-control" rows="1" id="exampleInputEmail11"></textarea>
        </div>
    <div class="form-group">
            <label for="exampleInputEmail12">Город</label>
            <textarea type="text" name="city"  class="form-control" rows="1" id="exampleInputEmail12"></textarea>
        </div>
    <div class="form-group">
            <label for="exampleInputEmail13">Введение</label>
            <textarea type="text" name="introduction"  class="form-control" rows="3" id="exampleInputEmail13"></textarea>
        </div>
    <div class="form-group">
            <label for="exampleInputEmail14">Основная часть</label>
            <textarea type="text" name="body"  class="form-control" rows="7" id="exampleInputEmail14"></textarea>
        </div>
    <div class="form-group">
            <label for="exampleInputEmail15">Заключение</label>
            <textarea type="text" name="conclusion"  class="form-control" rows="3" id="exampleInputEmail15"></textarea>
        </div>
    <div class="form-group">
            <label for="exampleInputEmail16">Спирсок использованных источников</label>
            <textarea type="text" name="literature"  class="form-control" rows="3" id="exampleInputEmail16"></textarea>
        </div>

<button type="submit" class="btn btn-primary" id="get">Получить файл</button>

</form>


{% endblock %}

app/templates/central/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'central/css/details.css' %}" type="text/css"/>
<div class="container">
    <img src="{{ details.image.url }}" class="image" alt="">

    <h5 class="">{{ details.name }}</h5>
    <p class="">{{ details.task }}</p>
    <p class="">{{ details.university }}</p>
    <p class="">{{ details.duration }}</p>
    <p class="">{{ details.date_of_start }}</p>
    <p class="">{{ details.date_of_finish }}</p>
    <p class="">{{ details.description }}</p>

    <form method="post">
    {% csrf_token %}

<a href="{% url 'app:add-to-course' details.pk %}" type="submit" class="btn btn-primary" id="get">Записаться на курс</a>

</form>
        </div>

{% endblock %}

app/templates/central/diploma.html
{% extends "base.html" %}
{% load static %}

{% block content %}

<link rel="stylesheet" href="{% static 'central/css/style.css' %}" type="text/css"/>


<p class="title">Дипломная работа</p>
<form method="post">
    {% csrf_token %}
    <div class="form-group">
    <label for="exampleInputEmail1">Университет</label>
    <input type="text" name="university" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
        <div class="form-group">
            <label for="exampleInputEmail2">Институт</label>
            <input type="text" name="institute" class="form-control" id="exampleInputEmail2" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail3">Кафедра</label>
            <input type="text" name="kafedra" class="form-control" id="exampleInputEmail3" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail4">Направление</label>
            <input type="text" name="way" class="form-control" id="exampleInputEmail4" aria-describedby="emailHelp">
        </div>
    <div class="form-group">
            <label for="exampleInputEmail5">Профиль</label>
            <input type="text" name="profile" class="form-control" id="exampleInputEmail5" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail6">Тема курсовой работы</label>
            <input type="text" name="task" class="form-control" id="exampleInputEmail6" aria-describedby="emailHelp">
        </div>
        <div class="form-group">
            <label for="exampleInputEmail7">Курс</label>
            <textarea type="text" name="number"  class="form-control" rows="1" id="exampleInputEmail7"></textarea>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail8">Номер группы</label>
            <textarea type="text" name="group"  class="form-control" rows="1" id="exampleInputEmail8"></textarea>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail9">Год</label>
            <textarea type="text" name="year"  class="form-control" rows="1" id="exampleInputEmail9"></textarea>
        </div>
        <div class="form-group">
            <label for="exampleInputEmai10">Фио студента</label>
            <textarea type="text" name="student"  class="form-control" rows="1" id="exampleInputEmai10"></textarea>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail11">Ученая степень преподавателя</label>
            <textarea type="text" name="degree"  class="form-control" rows="1" id="exampleInputEmail11"></textarea>
        </div>
    <div class="form-group">
            <label for="exampleInputEmail12">Фио преподавателя</label>
            <textarea type="text" name="teacher"  class="form-control" rows="1" id="exampleInputEmail12"></textarea>
        </div>
    <div class="form-group">
            <label for="exampleInputEmail13">Ученая степень заведующего кафедрой</label>
            <textarea type="text" name="degree_head"  class="form-control" rows="1" id="exampleInputEmail13"></textarea>
        </div>
    <div class="form-group">
            <label for="exampleInputEmail14">Фио заведующего кафедрой</label>
            <textarea type="text" name="head_teacher"  class="form-control" rows="1" id="exampleInputEmail14"></textarea>
        </div>
    <div class="form-group">
            <label for="exampleInputEmail15">Город</label>
            <textarea type="text" name="city"  class="form-control" rows="1" id="exampleInputEmail15"></textarea>
        </div>
    <div class="form-group">
            <label for="exampleInputEmail16">Введение</label>
            <textarea type="text" name="introduction"  class="form-control" rows="3" id="exampleInputEmail16"></textarea>
        </div>
    <div class="form-group">
            <label for="exampleInputEmail17">Основная часть</label>
            <textarea type="text" name="body"  class="form-control" rows="7" id="exampleInputEmail17"></textarea>
        </div>
    <div class="form-group">
            <label for="exampleInputEmail18">Заключение</label>
            <textarea type="text" name="conclusion"  class="form-control" rows="3" id="exampleInputEmail18"></textarea>
        </div>
    <div class="form-group">
            <label for="exampleInputEmail19">Спирсок использованных источников</label>
            <textarea type="text" name="literature"  class="form-control" rows="3" id="exampleInputEmail19"></textarea>
        </div>

<button type="submit" class="btn btn-primary" id="get">Получить файл</button>

</form>


{% endblock %}

app/templates/central/lesson.html
{% extends 'base.html' %}
{% load embed_video_tags %}
{% block content %}
<div class="container">
{% for lesson in lessons %}
    {% video lesson.video as my_video %}
      {% video my_video "large" %}
    {% endvideo %}
    <h5>Тема: {{ lesson.task }}</h5>
    <p>Название урока: {{ lesson.name }}</p>
    <p>Преподаватель: {{ lesson.teacher }}</p>
    <p>Домашнее задание: </p><a href="{{ lesson.homework }}">{{ lesson.homework }}</a>
    <p>Текущая оценка: {{ lesson.mark }}</p>
    <form method="post" action="{% url 'app:upload-video' %}" enctype="multipart/form-data">
    {% csrf_token %}
    {{ lesson_form.as_p }}
    <button type="submit" class="btn btn-primary">Загрузить</button>
    </form>
     {% endfor %}
</div>


{% endblock %}

app/templates/central/log_out.html
{% extends "base.html" %}

{% block content %}
<p>Выйти</p>

<a href="{% url 'app:login' %}">Клиените сюда, чттобы снова войти.</a>
{% endblock %}

app/templates/central/login.html
{% extends "base.html" %}
{% block title %}Log-in{% endblock %}
{% block content %}
    <h1>Log-in</h1>
    <p>Please, use the following form to log-in:</p>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Log-in"></p>
    </form>
{% endblock %}

app/templates/central/my_courses.html
{% extends "base.html" %}

{% block content %}
    <h1>Мои Курсы</h1>

    {% if course_user_list %}
    <ul>

      {% for course in course_user_list %}
<li>
        <a href="{% url 'app:lesson' %}">{{course.description_course.name}}</a>
</li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Вы пока не записаны ни на один курс</p>
    {% endif %}       
{% endblock %}

app/templates/central/register.html
{% extends "base.html" %}

{% block title %}Create an account{% endblock %}

{% block content %}
    <h1>Create an account</h1>
    <p>Please, sign up using the following form:</p>
    <form action="." method="post">
        {{ user_form.as_p }}
        {% csrf_token %}
        <p><input type="submit" value="Create my account"></p>
    </form>
    <p>Если вы уже зарегистрированы, то </p><a href="{% url 'app:login' %}">Войдите в систему</a>
{% endblock %}

app/templates/central/register_done.html
{% extends "base.html" %}

{% block title %}Welcome{% endblock %}

{% block content %}
    <h1>Welcome {{ new_user.first_name }}!</h1>
    <p>Your account has been successfully created. Now you can <a href="{% url 'app:login' %}">log in</a>.</p>
{% endblock %}